### ISSUE TITLE
replace assert error

### ISSUE THREAD

**Issue by HanJinChi** [comparch-security/FlexiCAS#151]
在分支debug-replacer下复现replacer的错误步骤如下：
- 首先编译：
`MODE=debug make regression -j`
- 之后重复运行该程序，直到发生assert报错(这个时间大概在1-2分钟)
` bash run.sh regression/multi-l2-msi`
可以看到是replacer的assert发生了报错

**Comment by HanJinChi** [comment]
我在分支debug-replacer下添加了global print以复现错误，复现步骤如下：
-首先编译：
`MODE=debug make pa_regression -j`
-之后重复运行多线程的程序，直到发生assert报错（这个过程很快，立马就能assert报错）

**Comment by HanJinChi** [comment]
![image](https://github.com/user-attachments/assets/0fbc31c3-5681-426a-9f11-6981e9c51385)
可以看到红框处, l1d-0的set 3出现了free_map和free_num不对应的情况，在这里正好出现了两个线程都要修改同一个set的replacer

**Comment by wsong83** [comment]
OK, this proof is enough to persuade me.

**Comment by wsong83** [comment]
This issue should be fixed by PR #155
